# Generated by Django 4.1.2 on 2023-12-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='항목명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='운동 설명')),
                ('type', models.CharField(choices=[(1, '측정'), (2, '운동')], max_length=1, verbose_name='항목 유형')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='영상')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
        ),
    ]
