# Generated by Django 4.1.2 on 2023-12-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('1', '측정'), ('2', '운동')], max_length=1, verbose_name='항목 유형'),
        ),
    ]
