# Generated by Django 4.1.2 on 2023-11-16 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Company Manager')], null=True, verbose_name='사용자 유형')),
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='아이디')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='기업명')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='기업 로고')),
                ('primary_color', models.CharField(default='#00b0a6', max_length=10, verbose_name='기업 주요 색상 RGB')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='type')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='user')),
                ('data', models.TextField(verbose_name='data')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='extra')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='수행일시')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='CompanyManager',
            fields=[
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='사번')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.company', verbose_name='기업')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('W', '여')], max_length=1, null=True, verbose_name='성별')),
                ('height', models.CharField(blank=True, max_length=3, null=True, verbose_name='신장')),
                ('weight', models.CharField(blank=True, max_length=3, null=True, verbose_name='체중')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.companymanager', verbose_name='담당자')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
