# Generated by Django 4.1.2 on 2023-11-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_client_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-created_at',)},
        ),
    ]
