# Generated by Django 4.1.2 on 2022-12-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='account_use_phone_664a69_idx'),
        ),
    ]
