# Generated by Django 4.1.2 on 2022-12-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_account_use_phone_664a69_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, null=True, verbose_name='user')),
                ('data', models.TextField(verbose_name='data')),
            ],
        ),
    ]
