# Generated by Django 4.1.2 on 2022-12-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_exerciselog_delete_walk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciselog',
            options={'ordering': ('-pk',)},
        ),
    ]
