# Generated by Django 4.1.2 on 2023-07-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_exerciselog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='extra'),
        ),
    ]
