# Generated by Django 4.1.2 on 2023-12-11 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_company_code_company_unique_company_code'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client', verbose_name='회원')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.companymanager', verbose_name='담당자')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_do_date', models.DateField(blank=True, null=True, verbose_name='수행 명령 일자')),
                ('did_exercise', models.BooleanField(default=False, verbose_name='수행 여부')),
                ('did_at', models.DateTimeField(blank=True, null=True, verbose_name='수행 일시')),
                ('set', models.IntegerField(blank=True, null=True, verbose_name='세트')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='횟수')),
                ('interval', models.IntegerField(blank=True, null=True, verbose_name='간격')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='처방 생성 일시')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.exercise', verbose_name='운동 항목')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription', verbose_name='처방')),
            ],
        ),
    ]
