# Generated by Django 4.1.2 on 2023-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmeasurement',
            name='exercise',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='측정 항목'),
        ),
    ]
